runtime: custom
env: flex

# Optional: Specify instance class
# instance_class: F2

# Optional: Configure health checks
# manual_scaling:
#   instances: 1

# Optional: Configure automatic scaling
# automatic_scaling:
#   min_num_instances: 1
#   max_num_instances: 2
#   cool_down_period_sec: 60
#   cpu_utilization:
#     target_utilization: 0.6
